name: audio_player_flutter
description: Apple Music / Tidal Style Audio Player for Flutter
version: 0.0.2+1

environment:
  sdk: ">=2.9.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.16.1
  built_collection: ^4.3.2
  built_value: ^7.1.0
  flutter_bloc: ^4.0.0
  http: ^0.12.2
  transparent_image: ^1.0.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_driver:
    sdk: flutter

  build_runner: ^1.9.0
  built_value_generator: ^7.1.0
  mockito: ^4.1.2
  pedantic: ^1.9.0
  test: ^1.14.3

flutter:
  uses-material-design: true